name: Sample App Tests
on: push
jobs:
  sample_app_tests:
    name: "Run Tests Using Jest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Clean install deps
        working-directory: ch5/sample-app
        run: |
          rm -rf node_modules
          npm install

      - name: Run tests (node)
        working-directory: ch5/sample-app
        run: node ./node_modules/jest/bin/jest.js --verbose
